version: 2.1

orbs:
  node: circleci/node@4.2.1

jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Check Node version
          command: node --version
      - run:
          name: Prettier check
          command: npm run format-check
      - run:
          name: TypeScript check
          command: npm run type-check

workflows:
  fumino_lint:
    jobs:
      - lint
