version: 2.1

orbs:
  node: circleci/node@4.2.1

jobs:
  lint:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-npm: false
          install-yarn: true
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Check Yarn version
          command: yarn --version
      - run:
          name: Check Node version
          command: node --version
      - run:
          name: Prettier check
          command: yarn format-check
      - run:
          name: ESLint check
          command: yarn eslint-check
      - run:
          name: TypeScript check
          command: yarn type-check

workflows:
  fumino_lint:
    jobs:
      - lint
