name: Next.js

on:
  pull_request:
    branches: [fumino]

jobs:
  next-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14', '16']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Prettier check
        run: yarn format-check

      - name: ESLint check
        run: yarn eslint-check

      - name: TypeScript check
        run: yarn type-check
